DROP TABLE IF EXISTS TBL_PARTICIPANTS;

CREATE TABLE TBL_PARTICIPANTS (
    id INT PRIMARY KEY,
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL,
    email VARCHAR(250) DEFAULT NULL
);