DROP TABLE IF EXISTS TBL_PARTICIPANTS;

CREATE TABLE TBL_PARTICIPANTS (
    code INT PRIMARY KEY,
    external_code INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    cpf VARCHAR(20) NOT NULL,
    phone VARCHAR(15) NULL,
    assign BOOLEAN NOT NULL,
    status BOOLEAN NOT NULL
);